BEGIN TRANSACTION;

INSERT INTO users (username,password_hash,role) VALUES ('user','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (username,password_hash,role) VALUES ('admin','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_ADMIN');
INSERT INTO users (username,password_hash,role) VALUES ('user1','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt4oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (username,password_hash,role) VALUES ('kevin','$2a$10$n4gb8t/RtMqToyZZuigeKeif18Z.3mnP5Vx/d3Zv9Nz93xHWr3Rni','ROLE_USER');


INSERT INTO album (registered_user_id, title, artist, year_released, genre, notes, album_image, create_date) VALUES
(2, 'Abbey Road', 'The Beatles', 1969, 'Rock', 'One of the most acclaimed albums in the history of popular music.', 'https://i.discogs.com/ffj9SJ3O75j7CiAA3QlvCMLSzqsFKaSq6N_U84eL5t8/rs:fit/g:sm/q:90/h:400/w:387/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEwNjU0/NTgzLTE1MDE3NzIx/MTktMTExOS5qcGVn.jpeg', NOW()),
(2, 'Back in Black', 'AC/DC', 1980, 'Rock', 'Best-selling album by a band, and the second best-selling album in history.', 'https://i.discogs.com/xf2PKezzQ243HuyRnERV8RTSzX_r9Nni7QZactGZjQY/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTQwMDU5/MS0xNTM3MDM1ODI5/LTEzOTEuanBlZw.jpeg', NOW()),
(1, 'The Dark Side of the Moon', 'Pink Floyd', 1973, 'Rock', 'Known for its complex themes and pioneering use of studio effects.', 'https://i.discogs.com/cO8d6DLOvOErJGhHe2InPDn28hZw0WQe4_8SpT03HtQ/rs:fit/g:sm/q:90/h:600/w:597/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE4NzMw/MTMtMTcxNTE3Mjcy/MC0xOTYwLmpwZWc.jpeg', NOW()),
(2, 'Thriller', 'Michael Jackson', 1982, 'Pop', 'Best-selling album of all time, with iconic hits like "Billie Jean".', 'https://i.discogs.com/dWe2AyguSxJpaaEWbK_mVLL3zs2ejuta0sJCx5BvS8o/rs:fit/g:sm/q:90/h:600/w:597/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI5MTEy/OTMtMTU5NDI0NTgx/Mi03OTMxLmpwZWc.jpeg', NOW()),
(1, 'Rumours', 'Fleetwood Mac', 1977, 'Rock', 'Critically acclaimed and known for its behind-the-scenes drama.', 'https://i.discogs.com/qp8AdVegG6noqqL5BzRA5e5-seqc052zMUp8-b082RM/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE0ODY2/Mzc2LTE1ODQ4ODg5/MDMtNDgzOS5qcGVn.jpeg', NOW()),
(1, 'Nevermind', 'Nirvana', 1991, 'Rock', 'Helped popularize the grunge movement and includes the hit "Smells Like Teen Spirit".', 'https://i.discogs.com/Iiq_s5Ox2zj0yyFtNCcxUPLSxN5G0VBO4UOgZIswBIA/rs:fit/g:sm/q:90/h:494/w:420/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTUyMzQ5/MzAtMTQxNjc0NTI4/NC00MTk0LmpwZWc.jpeg', NOW()),
(2, 'The Wall', 'Pink Floyd', 1979, 'Rock', 'A rock opera that explores themes of isolation and mental illness.', 'https://i.discogs.com/gvMsVECicK2YRlJ7S9wlbeLS2L_o39owUyYlv6JTc3w/rs:fit/g:sm/q:90/h:600/w:588/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI3Mzcx/ODU2LTE2ODY2NjQx/NzUtOTY5NC5qcGVn.jpeg', NOW()),
(1, 'Hotel California', 'Eagles', 1976, 'Rock', 'Features the iconic title track, which is one of the band''s signature songs.', 'https://i.discogs.com/PZz0RZth-jDXq_vEwv640MTGizMZe5KEc6KTzM6ZKzY/rs:fit/g:sm/q:90/h:600/w:596/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEzNTQ4/MTYtMTM4MzkwOTE3/MC0xNzEyLmpwZWc.jpeg', NOW()),
(1, 'Born to Run', 'Bruce Springsteen', 1975, 'Rock', 'Springsteen''s breakthrough album, which solidified his reputation.', 'https://i.discogs.com/Ea9chUPJxMvN1UFuJCE_SgQwJvVesuTm-hPEDkwrQKc/rs:fit/g:sm/q:90/h:336/w:336/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTQxMjA4/MjgtMTM1NTk2MzUy/MC04ODY1LmpwZWc.jpeg', NOW()),
(2, 'The Joshua Tree', 'U2', 1987, 'Rock', 'Widely regarded as U2''s magnum opus, with hits like "With or Without You".', 'https://i.discogs.com/C8-Haj94tKdA3vvHeWLF8HQ3SPVYr8po_ko_A_hPKto/rs:fit/g:sm/q:90/h:600/w:597/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEzNDE0/MzEtMTIxNTE1Mjgz/MC5qcGVn.jpeg', NOW()),
(2, 'Birth of the Cool', 'Miles Davis', 1957, 'Jazz', 'A landmark album in the cool jazz genre, featuring arrangements by Gil Evans and others.', 'https://i.discogs.com/5PjN3ERLk-bhldEaikIIpDjGOOCOhhSp5SqIYoNrERM/rs:fit/g:sm/q:90/h:596/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTU0NTY4/NTctMTQ0ODQzNTQ4/My04ODEzLmpwZWc.jpeg', NOW()),
(2, 'Time Out', 'The Dave Brubeck Quartet', 1959, 'Jazz', 'One of the best-selling jazz albums of all time, featuring the famous track "Take Five".', 'https://i.discogs.com/tz4tsa5_pTztKx_mWvRvKp7jZ2YyztvF69PTEmVFlLg/rs:fit/g:sm/q:90/h:600/w:591/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEyMzg0/NTAyLTE1NjQ4NDQ1/MTMtMTEwNi5qcGVn.jpeg', NOW()),
(2, 'Chet Baker Sings', 'Chet Baker', 1956, 'Jazz', 'An album showcasing Baker''s smooth vocals alongside his trumpet playing.', 'https://i.discogs.com/kkB3vl0JPI3BsUswgOzz474KcgJk3ItfKFbS03FFiLE/rs:fit/g:sm/q:90/h:600/w:596/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTExMDg0/NjUyLTE1MDk1NjE3/NzgtMjQ3My5qcGVn.jpeg', NOW()),
(1, 'Blue Train', 'John Coltrane', 1957, 'Jazz', 'Although Coltrane is more associated with hard bop, this album has cool jazz influences.', 'https://i.discogs.com/ebbggnVeaR0P2u7UGljGIVnhx1LaxVNMMZiyLvH2VrM/rs:fit/g:sm/q:90/h:505/w:500/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTgwNjcw/MDMtMTQ1NDUyODYy/My0zNDkwLmpwZWc.jpeg', NOW()),
(2, 'Kind of Blue', 'Miles Davis', 1959, 'Jazz', 'Widely regarded as one of the greatest jazz albums of all time.', 'https://i.discogs.com/wjjMk1xCKdaPbsUbaXWzHBNi3K-fmt3CYkQGqt0c_Z8/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTYyNzYx/ODMtMTY3NzAwMzM5/Ni0yMDQ1LmpwZWc.jpeg', NOW()),
(1, 'Getz/Gilberto', 'Stan Getz and João Gilberto', 1964, 'Jazz', 'A collaboration between Stan Getz and Brazilian musician João Gilberto, featuring the hit "The Girl from Ipanema".', 'https://i.discogs.com/snOjVGbcA1MCeUThkeMWLjRyl8zjOqQ2BFWclMBcET8/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE3MDg4/NC0xMzI0MjQ4OTkw/LmpwZWc.jpeg', NOW()),
(2, 'Jazz Impressions of Black Orpheus', 'Vince Guaraldi Trio', 1962, 'Jazz', 'Known for its relaxed and melodic style, this album features the famous track "Cast Your Fate to the Wind".', 'https://i.discogs.com/zmUY39mwv3arExqMq5XV3RJ-gu2gs1pX5IV9PC2AcGc/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMzMTUw/MTUtMTY2NDg3MTA0/NS01NzE5LnBuZw.jpeg', NOW()),
(1, 'The Sidewinder', 'Lee Morgan', 1964, 'Jazz', 'A pivotal album in both the hard bop and cool jazz genres.', 'https://i.discogs.com/aJPE1UkOs5TR_jM3dy0S2o_1ww3kOgIH2gZ0lPbbUCE/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTU3OTg1/Mi0xMzUyMDUwMTQ0/LTgzMDAuanBlZw.jpeg', NOW()),
(2, 'Cool Struttin', 'Sonny Clark', 1958, 'Jazz', 'A quintessential cool jazz album featuring notable performances by Art Farmer and Jackie McLean.', 'https://i.discogs.com/SF9iv5qmCN5JEgsvAfdVyigc8zJQYbViZ3nNv4b0eEc/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE0NDUz/NjItMTQzNzUwNzMz/NC02Nzk0LmpwZWc.jpeg', NOW()),
(1, 'The Sermon!', 'Jimmy Smith', 1959, 'Jazz', 'An album that combines cool jazz with elements of soul jazz, featuring Lee Morgan and Lou Donaldson.', 'https://i.discogs.com/E2rWWkK5c4B85pHLUT-Oakqs0PWMGmLC2uJaA51IRrw/rs:fit/g:sm/q:90/h:595/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE1ODE1/OTAzLTE1OTgzMTI4/ODItNDQwMS5qcGVn.jpeg', NOW()),
(2, 'Legend', 'Bob Marley and the Wailers', 1984, 'Reggae', 'The best-selling reggae album of all time, featuring hits like "No Woman, No Cry" and "Redemption Song".', 'https://i.discogs.com/vLVptBfro38CQ49Ox99ADJWXAesfPj5FvXgOQNnne-M/rs:fit/g:sm/q:90/h:594/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTUwOTIz/NS0xMjE2MTY4MTgz/LmpwZWc.jpeg', NOW()),
(2, 'Catch a Fire', 'Bob Marley and the Wailers', 1973, 'Reggae', 'The album that introduced Bob Marley to an international audience, known for tracks like "Stir It Up".', 'https://i.discogs.com/eO1-I700dfw92SXk0_KaDeBYewo_ly5kpoPsgI5kGvk/rs:fit/g:sm/q:90/h:433/w:450/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTc1Mzkw/OTEtMTQ0MzYwNTQ2/OS05OTc5LmpwZWc.jpeg', NOW()),
(2, 'Exodus', 'Bob Marley and the Wailers', 1977, 'Reggae', 'An iconic album that includes songs like "Jamming" and "One Love".', '', NOW()),
(2, 'Legalize It', 'Peter Tosh', 1976, 'Reggae', 'The debut album by Peter Tosh, advocating for the legalization of marijuana.', '', NOW()),
(2, 'Black Uhuru', 'Black Uhuru', 1980, 'Reggae', 'A seminal reggae album featuring the hit "Guess Who''s Coming to Dinner".', '', NOW()),
(2, 'War Inna Babylon', 'Max Romeo', 1976, 'Reggae', 'Produced by Lee "Scratch" Perry, this album is known for its politically charged lyrics.', '', NOW()),
(2, 'Two Sevens Clash', 'Culture', 1977, 'Reggae', 'A classic roots reggae album that predicted apocalypse in 1977.', 'https://i.discogs.com/_OC-IUEPqf4HQ47JoJnPislkdLNFAsYoa2_IysLCS0c/rs:fit/g:sm/q:90/h:600/w:599/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEzMjE5/ODUxLTE1NTAxODAy/OTItMzAyNS5qcGVn.jpeg', NOW()),
(2, 'Night Nurse', 'Gregory Isaacs', 1982, 'Reggae', 'A smooth reggae album featuring the popular title track "Night Nurse".', 'https://i.discogs.com/8azAbL0Uxj4CkUFCUhQEEB4NH-g3VxmItBzxYsbRLoU/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTQ1NTAz/MC0xNDE1NTgwNjc1/LTI4MzUuanBlZw.jpeg', NOW()),
(2, 'Police and Thieves', 'Junior Murvin', 1977, 'Reggae', 'A classic reggae album produced by Lee "Scratch" Perry, with the hit title track "Police and Thieves".', '', NOW()),
(2, 'The Harder They Come', 'Various Artists', 1972, 'Reggae', 'The soundtrack to the film "The Harder They Come," featuring Jimmy Cliff and other reggae legends.', '', NOW()),
(2, 'Buena Vista Social Club', 'Buena Vista Social Club', 1997, 'Latin', 'A Grammy-winning album that brought together Cuban musicians for a historic recording.', '', NOW()),
(2, 'Abraxas', 'Santana', 1970, 'Latin Rock', 'Featuring the hit "Black Magic Woman", this album blends rock with Latin rhythms.', '', NOW()),
(2, 'Mi Tierra', 'Gloria Estefan', 1993, 'Latin Pop', 'Gloria Estefan''s homage to her Cuban roots, blending pop with traditional Cuban music.', '', NOW()),
(2, 'Amar Sin Mentiras', 'Marc Anthony', 2004, 'Latin Pop', 'A Grammy-winning album by Marc Anthony, known for its romantic ballads.', '', NOW()),
(2, 'El Mal Querer', 'Rosalía', 2018, 'Flamenco Pop', 'A groundbreaking album that blends traditional flamenco with contemporary pop and urban music.', '', NOW()),
(2, 'La Vida Es Un Carnaval', 'Celia Cruz', 1998, 'Salsa', 'One of Celia Cruz''s most iconic albums, featuring the hit "La Vida Es Un Carnaval".', '', NOW()),
(2, 'Segundo Romance', 'Luis Miguel', 1994, 'Bolero', 'The second album in Luis Miguel''s bolero trilogy, featuring classic Latin love songs.', '', NOW()),
(2, 'Fabulosos Calavera', 'Los Fabulosos Cadillacs', 1997, 'Latin Rock', 'An eclectic album mixing rock, ska, and Latin rhythms.', '', NOW()),
(2, 'Café Tacuba', 'Café Tacuba', 1992, 'Rock en Español', 'The debut album by one of Mexico''s most influential rock bands.', '', NOW()),
(2, 'Bachata Rosa', 'Juan Luis Guerra', 1990, 'Bachata', 'A landmark album that popularized the bachata genre internationally.', '', NOW()),
(2, 'Discovery', 'Daft Punk', 2001, 'Electronic Dance Music', 'A landmark album in the EDM genre, featuring hits like "One More Time" and "Harder, Better, Faster, Stronger".', '', NOW()),
(2, 'Random Access Memories', 'Daft Punk', 2013, 'Electronic Dance Music', 'This album includes the Grammy-winning hit "Get Lucky" and marked Daft Punk''s exploration of live instrumentation.', '', NOW()),
(2, 'Play', 'Moby', 1999, 'Electronic Dance Music', 'An album that brought electronic music to the mainstream, featuring tracks like "Porcelain" and "Natural Blues".', '', NOW()),
(2, 'Immersion', 'Pendulum', 2010, 'Drum and Bass', 'A powerful fusion of drum and bass with rock and electronic elements.', '', NOW()),
(2, '18 Months', 'Calvin Harris', 2012, 'Electronic Dance Music', 'Featuring collaborations with artists like Rihanna and Ellie Goulding, this album produced several chart-topping singles.', '', NOW()),
(2, 'We Are All We Need', 'Above & Beyond', 2015, 'Trance', 'An acclaimed trance album that includes hits like "Sticky Fingers" and "Blue Sky Action".', '', NOW()),
(2, 'For Lack of a Better Name', 'deadmau5', 2009, 'Progressive House', 'Featuring the iconic track "Ghosts n Stuff", this album solidified deadmau5''s status in the EDM scene.', '', NOW()),
(2, 'Born This Way: The Remix', 'Lady Gaga', 2011, 'Electronic Dance Music', 'A remix album of Lady Gaga''s "Born This Way", featuring remixes by artists like Zedd and The Weeknd.', '', NOW()),
(2, 'Syro', 'Aphex Twin', 2014, 'IDM', 'Aphex Twin''s return to music after a long hiatus, featuring his signature complex and experimental sound.', '', NOW()),
(2, 'Haunted Dancehall', 'The Sabres of Paradise', 1994, 'Electronic Dance Music', 'An influential album in the development of ambient and electronic music.', '', NOW()),
(2, 'The Four Seasons', 'Antonio Vivaldi', 1725, 'Classical', 'A set of four violin concertos representing the seasons of the year.', '', NOW()),
(2, 'Symphony No. 9', 'Ludwig van Beethoven', 1824, 'Classical', 'Known as the Choral Symphony, featuring the famous "Ode to Joy" in the final movement.', '', NOW()),
(2, 'The Well-Tempered Clavier', 'Johann Sebastian Bach', 1722, 'Classical', 'A collection of solo keyboard music consisting of two volumes of preludes and fugues in all major and minor keys.', '', NOW()),
(2, 'Requiem', 'Wolfgang Amadeus Mozart', 1791, 'Classical', 'Mozart''s final composition, left incomplete at his death and later completed by Franz Xaver Süssmayr.', '', NOW()),
(2, 'Piano Concerto No. 21', 'Wolfgang Amadeus Mozart', 1785, 'Classical', 'A well-known piano concerto with a lyrical second movement, often referred to as the "Elvira Madigan" concerto.', '', NOW()),
(2, 'Symphony No. 40', 'Wolfgang Amadeus Mozart', 1788, 'Classical', 'One of Mozart''s most famous symphonies, known for its emotional depth and dramatic character.', '', NOW()),
(2, 'Pictures at an Exhibition', 'Modest Mussorgsky', 1874, 'Classical', 'A suite of ten piano pieces that was later orchestrated by Maurice Ravel, depicting a visit to an art exhibition.', '', NOW()),
(2, 'Symphony No. 5', 'Gustav Mahler', 1904, 'Classical', 'A major symphonic work known for its emotional range and the famous Adagietto movement.', 'https://i.discogs.com/tnnWY8R9cCeTo0_vayoZyQ7lkCwqKeWyjj0ICUVTY5M/rs:fit/g:sm/q:90/h:600/w:590/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE5MDIz/NjUtMTI1MTI1ODU2/NC5qcGVn.jpeg', NOW()),
(2, 'The Brandenburg Concertos', 'Johann Sebastian Bach', 1721, 'Classical', 'A set of six concertos considered one of the greatest achievements in Baroque music.', '', NOW()),
(2, 'Carmen', 'Georges Bizet', 1875, 'Classical', 'An opera known for its vibrant and passionate music, including the famous Habanera and Toreador Song.', '', NOW()),
(2, 'Red Headed Stranger', 'Willie Nelson', 1975, 'Country', 'A classic concept album that is considered one of Willie Nelson''s greatest works.', 'https://i.discogs.com/fhat5CADYWANhC1T0U-kY4l9dmgeU2VCB0HtMVVqWVQ/rs:fit/g:sm/q:90/h:598/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE1NjA0/NTAtMTUzOTgzNjE4/OC01OTMzLmpwZWc.jpeg', NOW()),
(2, 'The Complete Hank Williams', 'Hank Williams', 1951, 'Country', 'A comprehensive collection of Hank Williams'' early recorings, showcasing his influential style.', '', NOW()),
(2, 'Greatest Hits', 'Johnny Cash', 1967, 'Country', 'A compilation album featuring some of Johnny Cash''s most iconic songs from the 1950s and 1960s.', '', NOW()),
(2, 'Come On Over', 'Shania Twain', 1997, 'Country', 'One of the best-selling country albums of all time, known for hits like "You''re Still the One".', '', NOW()),
(2, 'Aerials', 'Alan Jackson', 1994, 'Country', 'An album that features some of Alan Jackson''s most beloved tracks, including "Chattahoochee".', '', NOW()),
(2, 'The Gambler', 'Kenny Rogers', 1978, 'Country', 'Featuring the iconic title track "The Gambler", this album became one of Kenny Rogers'' most successful releases.', 'https://i.discogs.com/GOA9lxitECEoiTeJdT_7zKk5cAwpZzC9pZcZo0_kR1I/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTg5MDkx/Ni0xMzU2NTUxMzUx/LTc4MDIuanBlZw.jpeg', NOW()),
(2, 'Tangled Up in Blue', 'Bob Dylan', 1975, 'Country', 'Although primarily a rock album, it features country influences and is considered a classic in the genre.', 'https://i.discogs.com/wrItLkoa_RFoDIihIIGneRPIZxgnQvmhqYcfZJiIgOo/rs:fit/g:sm/q:90/h:593/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTIxMzM5/MjAtMTM0MTE5NTAz/Mi05MDY4LmpwZWc.jpeg', NOW()),
(2, 'Coal Miner''s Daughter', 'Loretta Lynn', 1970, 'Country', 'An autobiographical album by Loretta Lynn that became a defining work in her career.', '', NOW()),
(2, 'No Fences', 'Garth Brooks', 1990, 'Country', 'A landmark album in Garth Brooks'' career featuring hits like "Friends in Low Places".', '', NOW()),
(2, 'Pride', 'The Judds', 1984, 'Country', 'An album that helped solidify The Judds as one of the leading acts in country music.', '', NOW()),
(2, 'Songs in the Key of Life', 'Stevie Wonder', 1976, 'R&B', 'An acclaimed double album featuring hits like "Isn''t She Lovely" and "Sir Duke".', '', NOW()),
(2, 'Confessions', 'Usher', 2004, 'R&B', 'A defining album of Usher''s career with hits such as "Yeah!" and "Burn".', '', NOW()),
(2, 'The Miseducation of Lauryn Hill', 'Lauryn Hill', 1998, 'R&B', 'A groundbreaking album blending R&B, hip-hop, and soul, including tracks like "Doo Wop (That Thing)".', '', NOW()),
(2, 'Channel Orange', 'Frank Ocean', 2012, 'R&B', 'A critically acclaimed album known for its genre-blending style and tracks like "Thinkin Bout You".', '', NOW()),
(2, 'Back to Black', 'Amy Winehouse', 2006, 'R&B', 'Featuring a vintage sound and hits like "Rehab" and "You Know I''m No Good".', '', NOW()),
(2, 'Whitney', 'Whitney Houston', 1987, 'R&B', 'An iconic album featuring classics like "I Wanna Dance with Somebody" and "Didn''t We Almost Have It All".', '', NOW()),
(2, 'Voodoo', 'D''Angelo', 2000, 'R&B', 'A critically acclaimed album known for its soulful and jazzy elements, including "Untitled (How Does It Feel)".', '', NOW()),
(2, 'Love Deluxe', 'Sade', 1992, 'R&B', 'An album featuring smooth, soulful tracks like "No Ordinary Love" and "Kiss of Life".', '', NOW()),
(2, 'Goodies', 'Ciara', 2004, 'R&B', 'The debut album from Ciara with hits like "Goodies" and "1, 2 Step".', '', NOW()),
(2, 'Rihanna', 'Rated R', 2009, 'R&B', 'An album showcasing a darker and edgier side of Rihanna with tracks like "Russian Roulette".', 'https://i.discogs.com/cOz0vUhtp7l-OJZuzkuVcCBqjfyqh2j0jaDfNdOTQEU/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTcwOTUw/MzktMTQzMzYwNjE0/Mi05ODQwLmpwZWc.jpeg', NOW()),
(2, 'Led Zeppelin IV', 'Led Zeppelin', 1971, 'Rock', 'Featuring iconic tracks like "Stairway to Heaven" and "Black Dog".', 'https://i.discogs.com/yFq3X0xZMxIVHIFgmbrsPvJHXLJCfVLWs60AL4XS4bs/rs:fit/g:sm/q:90/h:598/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEwMTU0/NjUtMTM2NjMxMTg2/Ny0yNzg1LmpwZWc.jpeg', NOW()),
(2, 'A Night at the Opera', 'Queen', 1975, 'Rock', 'Known for the operatic epic "Bohemian Rhapsody".', 'https://i.discogs.com/2GXnNYolz0ciUnj8-ycSwQ8Uuy0Qu7LCfiZivZ0p_bo/rs:fit/g:sm/q:90/h:594/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTYxMjc4/MC0xNTQxMzY3MTQ1/LTIxMjcuanBlZw.jpeg', NOW()),
(2, 'Born in the U.S.A.', 'Bruce Springsteen', 1984, 'Rock', 'An album that became a cultural landmark with tracks like "Dancing in the Dark".', '', NOW()),
(2, 'Appetite for Destruction', 'Guns N'' Roses', 1987, 'Rock', 'A groundbreaking debut album with hits like "Sweet Child O'' Mine" and "Welcome to the Jungle".', 'https://i.discogs.com/VQy0HOhX4RiGLIg0LXi-RiZMJG8wtJDvFaBbarerjyA/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM4Mzc3/Ny0xMTczNTQzMzU5/LmpwZWc.jpeg', NOW()),
(2, 'The Rise and Fall of Ziggy Stardust and the Spiders from Mars', 'David Bowie', 1972, 'Rock', 'A concept album that introduced the world to Bowie''s alter ego Ziggy Stardust.', '', NOW()),
(2, 'Sticky Fingers', 'The Rolling Stones', 1971, 'Rock', 'Featuring hits like "Brown Sugar" and "Wild Horses", this album is a classic of the Stones'' catalog.', '', NOW()),
(2, 'London Calling', 'The Clash', 1979, 'Rock', 'A landmark punk rock album that blends various styles and political themes.', '', NOW()),
(2, 'Who''s Next', 'The Who', 1971, 'Rock', 'An influential album featuring classic rock anthems like "Baba O''Riley" and "Behind Blue Eyes".', 'https://i.discogs.com/g97FVTu96ctj-AOw2zjmJrz3I2ZPyipQuWwUgFQ_YlI/rs:fit/g:sm/q:90/h:600/w:596/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTQ4NzQ2/NC0xNTg3Mzc2MjQw/LTQ5NDEuanBlZw.jpeg', NOW()),
(2, 'Doolittle', 'Pixies', 1989, 'Rock', 'Known for its unique sound and influence on alternative rock, including tracks like "Monkey Gone to Heaven".', '', NOW()),
(2, 'Californication', 'Red Hot Chili Peppers', 1999, 'Rock', 'Marked the return of guitarist John Frusciante and includes hits like "Scar Tissue" and "Otherside".', 'https://i.discogs.com/CyHLgusU6vKUZ6AZbiWlLpgtKm2mT05k0NdV5LQvMjM/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEyNjY4/MDQtMTQ2MTI5MDIx/Ni03MDEwLmpwZWc.jpeg', NOW()),
(2, 'Thriller', 'Michael Jackson', 1982, 'Pop', 'Best-selling album of all time, with iconic hits like "Billie Jean" and "Thriller".', '', NOW()),
(2, '1989', 'Taylor Swift', 2014, 'Pop', 'Marked Taylor Swift''s transition from country to pop, featuring hits like "Shake It Off".', '', NOW()),
(2, 'Future Nostalgia', 'Dua Lipa', 2020, 'Pop', 'A critically acclaimed album known for its disco-influenced sound and hits like "Don''t Start Now".', '', NOW()),
(2, 'The Fame', 'Lady Gaga', 2008, 'Pop', 'Debut album featuring hits like "Just Dance" and "Poker Face".', '', NOW()),
(2, 'Like a Virgin', 'Madonna', 1984, 'Pop', 'An album that solidified Madonna''s status as a pop icon with hits like "Material Girl".', 'https://i.discogs.com/GK85qS-oBUfj_8rjFHQaO73HW16U51qRS5EEV5ZDuGg/rs:fit/g:sm/q:90/h:595/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTQyODk0/MDgtMTQxODg4NjE4/NC0xMjc2LmpwZWc.jpeg', NOW()),
(2, 'Lover', 'Taylor Swift', 2019, 'Pop', 'An album characterized by its romantic themes and hits like "Lover" and "You Need to Calm Down".', '', NOW()),
(2, 'Confessions on a Dance Floor', 'Madonna', 2005, 'Pop', 'Known for its electronic dance beats and hits like "Hung Up".', '', NOW()),
(2, 'Anti', 'Rihanna', 2016, 'Pop', 'Features a mix of pop and R&B with hits like "Work".', '', NOW()),
(2, 'Rainbow', 'Kesha', 2017, 'Pop', 'An album reflecting a more personal and emotional side of Kesha, featuring "Praying".', '', NOW()),
(2, 'Sweetener', 'Ariana Grande', 2018, 'Pop', 'An album known for its upbeat tracks and the hit single "Thank U, Next".', '', NOW()),
(2, 'Christmas', 'Michael Bublé', 2011, 'Holiday', 'A popular modern holiday album featuring classics like "All I Want for Christmas Is You".', 'https://i.discogs.com/G6TvFR3BZ2YUT0puLXveM2xgxjfT-s62VzDPFtcL2rE/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMxOTU1/MTItMTMyNDc5NDgz/Ny5qcGVn.jpeg', NOW()),
(2, 'Let It Snow', 'Frank Sinatra', 1957, 'Holiday', 'A classic holiday album with Sinatra''s smooth vocals on traditional Christmas songs.', 'https://i.discogs.com/4eU3Qp6vFc5t9bSvFUbLnzSN80C6ReUYjlt8Ppoqxew/rs:fit/g:sm/q:90/h:600/w:591/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI0Nzcx/NzQ5LTE2NjUzNDUz/NjQtMjI3Ny5qcGVn.jpeg', NOW()),
(2, 'Holiday', 'Madonna', 1983, 'Holiday', 'Features Madonna''s hit holiday single "Holiday" and other festive tracks.', '', NOW()),
(2, 'A Charlie Brown Christmas', 'Vince Guaraldi Trio', 1965, 'Holiday', 'Iconic jazz album from the beloved Peanuts special, featuring "Linus and Lucy".', 'https://i.discogs.com/fX8wAS69mRFpoLgU4Gy_sNjQ7BzSOHs1z8EzPbutnr4/rs:fit/g:sm/q:90/h:570/w:568/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE2Mjc3/MzEtMTMzNjYzMTg4/MC01MDQ5LmpwZWc.jpeg', NOW()),
(2, 'Merry Christmas', 'Mariah Carey', 1994, 'Holiday', 'One of the best-selling holiday albums of all time, including the hit "All I Want for Christmas Is You".', 'https://i.discogs.com/08wNoRk1F5qZRH-lqZNqPs-svvjW23bFN8U04MAJ89s/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEyNDcx/OTYtMTQyMjU0MTgw/MC00ODgwLmpwZWc.jpeg', NOW()),
(2, 'The Christmas Song', 'Nat King Cole', 1960, 'Holiday', 'Includes the timeless classic "The Christmas Song (Chestnuts Roasting on an Open Fire)".', 'https://i.discogs.com/tizWkEL_MIn6Wqg1rvYnUq_DJDlQ4HNfIG1SdS3JcuM/rs:fit/g:sm/q:90/h:597/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTcyMjM1/OC0xMjcwODQzODU3/LmpwZWc.jpeg', NOW()),
(2, 'Christmas with the Rat Pack', 'Frank Sinatra, Dean Martin, Sammy Davis Jr.', 1960, 'Holiday', 'A collection of holiday tunes from the legendary Rat Pack.', 'https://i.discogs.com/t1Bb4N2EZGtMKEy5WixKlzxRTvh_79sjvRUL-mDui_A/rs:fit/g:sm/q:90/h:600/w:591/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTQxNzAw/ODEtMTQyNjk5MTE4/MC04MjExLmpwZWc.jpeg', NOW()),
(2, 'White Christmas', 'Bing Crosby', 1942, 'Holiday', 'Featuring the classic title track "White Christmas", a staple of holiday music.', 'https://i.discogs.com/tiDi3f24k8IE0qrJ91dBPBFco_jISWgSvSytoxmly-0/rs:fit/g:sm/q:90/h:600/w:598/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM5NDU3/NjYtMTQ3NTI2Mzkx/NC03MDM1LmpwZWc.jpeg', NOW()),
(2, 'Christmas Kisses', 'Ariana Grande', 2013, 'Holiday', 'An EP featuring Ariana Grande''s take on classic holiday songs.', 'https://i.discogs.com/p4P_-_rnGCjrSpaxXKM6J32O_i2POIFy03MXsvhAHPM/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTUyMjM2/MjMtMTM4Nzk5ODYw/Ni00MzYzLmpwZWc.jpeg', NOW()),
(2, 'Elf: Original Motion Picture Soundtrack', 'Various Artists', 2003, 'Holiday', 'Soundtrack from the popular holiday film "Elf", including festive songs from various artists.', 'https://i.discogs.com/Fca73iLIngXUxeu1FZ_pO9b74KwrbQy6Pr9MLxSg5R8/rs:fit/g:sm/q:90/h:595/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTIyNDg0/MTU5LTE2OTY3NjU4/MjEtMjc2NS5qcGVn.jpeg', NOW()),
(2, 'Animals', 'Pink Floyd', 1977, 'Rock', 'A concept album with themes of societal criticism and animal imagery.', 'https://i.discogs.com/_hYJ-UiHBq0KtuIlz26o-4Ar82o9589HIFIE5XOXuVU/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM5MTMy/Mi0xNjkxNTYzMjc4/LTYwODAuanBlZw.jpeg', NOW()),
(2, 'Wish You Were Here', 'Pink Floyd', 1975, 'Rock', 'Famous for its title track and "Shine On You Crazy Diamond", a tribute to Syd Barrett.', 'https://i.discogs.com/pZnTKUeiKsxSyvX_87YMgccx0bq5sjqThFH9iSNAtAY/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE2MjEx/ODEyLTE2MzczMzYw/OTctOTI4MC5qcGVn.jpeg', NOW()),
(2, 'Meddle', 'Pink Floyd', 1971, 'Rock', 'Known for the epic track "Echoes", which dominates the second half of the album.', 'https://i.discogs.com/nlcHURJ-xZgDIezGAne4lRoiOZJYbb-qHxf7NMfwTQw/rs:fit/g:sm/q:90/h:592/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTQxMzc0/OTMtMTUzNzIxNjkz/NS05NzUzLmpwZWc.jpeg', NOW()),
(2, 'The Piper at the Gates of Dawn', 'Pink Floyd', 1967, 'Rock', 'The debut album, characterized by its psychedelic sound and Syd Barrett''s influence.', 'https://i.discogs.com/hb2vfQoi-csFMlMpGEHrDNUFVlOnLUVQgWYyFyXOQNs/rs:fit/g:sm/q:90/h:596/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI5MDEy/MDMtMTYwNzE4NTk0/OS0xNDMxLmpwZWc.jpeg', NOW()),
(2, 'A Saucerful of Secrets', 'Pink Floyd', 1968, 'Rock', 'The second album, which marks the beginning of the transition from Syd Barrett to David Gilmour.', 'https://i.discogs.com/Jcs2saffPTQvg8a4HmnhdagkrChDcewBA5Xj0tum9Sk/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEzODIz/ODctMTU1NTU0MzU4/Ny00NzAzLmpwZWc.jpeg', NOW()),
(2, 'Obscured by Clouds', 'Pink Floyd', 1972, 'Rock', 'A soundtrack album for the film "La Vallée", featuring a mix of rock and instrumental tracks.', 'https://i.discogs.com/c1B9Jw9ruSJqyp42-VkC2cxSyzq7LMQI7GztAeIkmrA/rs:fit/g:sm/q:90/h:600/w:597/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMwOTI0/MTItMTMxNTM1MTI4/OS5qcGVn.jpeg', NOW()),
(2, 'The Final Cut', 'Pink Floyd', 1983, 'Rock', 'A concept album and the last album with Roger Waters, focusing on themes of war and politics.', 'https://i.discogs.com/nQ9TyddcSe2CL0rjRlvQIW8ShAeO7eBAEjE6BRpH5Hg/rs:fit/g:sm/q:90/h:600/w:566/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEyMDYx/MzQtMTMxODA5MDc3/Ni5qcGVn.jpeg', NOW()),
(2, 'Momentary Lapse of Reason', 'Pink Floyd', 1987, 'Rock', 'The first album after Roger Waters left the band, featuring a more polished and electronic sound.', 'https://i.discogs.com/9cWYbmG22n9I5X2Pfz4_U3pscmLpy1gffxZQwswIG4Q/rs:fit/g:sm/q:90/h:595/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEyMDE3/NzItMTQ0NTIyNTY5/Ni0yNjg1LmpwZWc.jpeg', NOW()),
(2, 'Paranoid', 'Black Sabbath', 1970, 'Rock', 'One of the pioneering albums of heavy metal.', 'https://i.discogs.com/IktWj7o-ctHsGt3t-9cvGWCqUhh33G-tVgixfHKA6dA/rs:fit/g:sm/q:90/h:564/w:575/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTY5Njc3/Mi0xMzg5NjIyMTk4/LTU3MzUuanBlZw.jpeg', NOW()),
(2, 'Master of Puppets', 'Metallica', 1986, 'Rock', 'Highly influential metal album featuring complex compositions.', 'https://i.discogs.com/WIcmVaAsfOwxgaKApPMciVitogXJEkSAl1TyIhxTNRw/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE1NDk2/MzYtMTI2NTk0ODA5/NC5qcGVn.jpeg', NOW()),
(2, 'The Number of the Beast', 'Iron Maiden', 1982, 'Rock', 'Iconic album featuring classic heavy metal themes.', 'https://i.discogs.com/-wHpEmzsOPDHv755TdLKf4a4rS0i-zCmrdu8492KxOk/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE0NjYy/OTktMTY0NTU0MTQx/NC0yNDk0LmpwZWc.jpeg', NOW()),
(2, 'Painkiller', 'Judas Priest', 1990, 'Rock', 'Known for its speed metal influences and powerful vocals.', 'https://i.discogs.com/-OfsxmQv-4D21nNeludWOwFvtMTQYVJIhc8_cT8PKbE/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE2MTIy/OTItMTU5NTg5NDkx/My0zOTQ1LmpwZWc.jpeg', NOW()),
(2, 'British Steel', 'Judas Priest', 1980, 'Rock', 'A landmark album in the heavy metal genre with a more accessible sound.', 'https://i.discogs.com/-Ms8k-yQdyAuHuXgAN0b6nlJYLtZF8a0kP4DnSEGVBA/rs:fit/g:sm/q:90/h:597/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE1Njgw/ODEtMTY5MzQxODAw/My05NDMwLmpwZWc.jpeg', NOW()),
(2, 'Reign in Blood', 'Slayer', 1986, 'Rock', 'A seminal album in thrash metal with intense speed and aggression.', 'https://i.discogs.com/ssK5RzyVR9-gBLkS40Fybz5QTvvVsaHiXj9lGfvf0Ew/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM3NzUy/MS0xNjM5MjM4OTg2/LTU1MDMuanBlZw.jpeg', NOW()),
(2, 'Hell Awaits', 'Slayer', 1985, 'Rock', 'Famous for its dark themes and complex arrangements.', 'https://i.discogs.com/S2vkQq_tAqfEulYGJF0KtZ4Q6VNSjqXFCVk_s9MONf0/rs:fit/g:sm/q:90/h:596/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEwMjY3/MTMtMTYzNDY0OTE4/MS0zMjg1LmpwZWc.jpeg', NOW()),
(2, 'Holy Diver', 'Dio', 1983, 'Rock', 'Featuring classic heavy metal sound with powerful vocals and fantasy themes.', 'https://i.discogs.com/Tebkvc5nA9AyMVaxBHgLRnVQFEjP6HZEe81vCrjZGdA/rs:fit/g:sm/q:90/h:598/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEzMzE2/Mzg1LTE2NDg1Mzg3/MTctNTcyMC5qcGVn.jpeg', NOW()),

(4, 'Abbey Road', 'The Beatles', 1969, 'Rock', 'One of the most acclaimed albums in the history of popular music.', 'https://i.discogs.com/ffj9SJ3O75j7CiAA3QlvCMLSzqsFKaSq6N_U84eL5t8/rs:fit/g:sm/q:90/h:400/w:387/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEwNjU0/NTgzLTE1MDE3NzIx/MTktMTExOS5qcGVn.jpeg', NOW()),
(4, 'Back in Black', 'AC/DC', 1980, 'Rock', 'Best-selling album by a band, and the second best-selling album in history.', 'https://i.discogs.com/xf2PKezzQ243HuyRnERV8RTSzX_r9Nni7QZactGZjQY/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTQwMDU5/MS0xNTM3MDM1ODI5/LTEzOTEuanBlZw.jpeg', NOW()),
(4, 'The Dark Side of the Moon', 'Pink Floyd', 1973, 'Rock', 'Known for its complex themes and pioneering use of studio effects.', 'https://i.discogs.com/cO8d6DLOvOErJGhHe2InPDn28hZw0WQe4_8SpT03HtQ/rs:fit/g:sm/q:90/h:600/w:597/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE4NzMw/MTMtMTcxNTE3Mjcy/MC0xOTYwLmpwZWc.jpeg', NOW()),
(4, 'Thriller', 'Michael Jackson', 1982, 'Pop', 'Best-selling album of all time, with iconic hits like "Billie Jean".', 'https://i.discogs.com/dWe2AyguSxJpaaEWbK_mVLL3zs2ejuta0sJCx5BvS8o/rs:fit/g:sm/q:90/h:600/w:597/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI5MTEy/OTMtMTU5NDI0NTgx/Mi03OTMxLmpwZWc.jpeg', NOW()),
(4, 'Rumours', 'Fleetwood Mac', 1977, 'Rock', 'Critically acclaimed and known for its behind-the-scenes drama.', 'https://i.discogs.com/qp8AdVegG6noqqL5BzRA5e5-seqc052zMUp8-b082RM/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE0ODY2/Mzc2LTE1ODQ4ODg5/MDMtNDgzOS5qcGVn.jpeg', NOW()),
(4, 'Nevermind', 'Nirvana', 1991, 'Rock', 'Helped popularize the grunge movement and includes the hit "Smells Like Teen Spirit".', 'https://i.discogs.com/Iiq_s5Ox2zj0yyFtNCcxUPLSxN5G0VBO4UOgZIswBIA/rs:fit/g:sm/q:90/h:494/w:420/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTUyMzQ5/MzAtMTQxNjc0NTI4/NC00MTk0LmpwZWc.jpeg', NOW()),
(4, 'The Wall', 'Pink Floyd', 1979, 'Rock', 'A rock opera that explores themes of isolation and mental illness.', 'https://i.discogs.com/gvMsVECicK2YRlJ7S9wlbeLS2L_o39owUyYlv6JTc3w/rs:fit/g:sm/q:90/h:600/w:588/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI3Mzcx/ODU2LTE2ODY2NjQx/NzUtOTY5NC5qcGVn.jpeg', NOW()),
(4, 'Hotel California', 'Eagles', 1976, 'Rock', 'Features the iconic title track, which is one of the band''s signature songs.', 'https://i.discogs.com/PZz0RZth-jDXq_vEwv640MTGizMZe5KEc6KTzM6ZKzY/rs:fit/g:sm/q:90/h:600/w:596/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEzNTQ4/MTYtMTM4MzkwOTE3/MC0xNzEyLmpwZWc.jpeg', NOW()),
(4, 'Born to Run', 'Bruce Springsteen', 1975, 'Rock', 'Springsteen''s breakthrough album, which solidified his reputation.', 'https://i.discogs.com/Ea9chUPJxMvN1UFuJCE_SgQwJvVesuTm-hPEDkwrQKc/rs:fit/g:sm/q:90/h:336/w:336/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTQxMjA4/MjgtMTM1NTk2MzUy/MC04ODY1LmpwZWc.jpeg', NOW()),
(4, 'The Joshua Tree', 'U2', 1987, 'Rock', 'Widely regarded as U2''s magnum opus, with hits like "With or Without You".', 'https://i.discogs.com/C8-Haj94tKdA3vvHeWLF8HQ3SPVYr8po_ko_A_hPKto/rs:fit/g:sm/q:90/h:600/w:597/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEzNDE0/MzEtMTIxNTE1Mjgz/MC5qcGVn.jpeg', NOW()),
(4, 'Birth of the Cool', 'Miles Davis', 1957, 'Jazz', 'A landmark album in the cool jazz genre, featuring arrangements by Gil Evans and others.', 'https://i.discogs.com/5PjN3ERLk-bhldEaikIIpDjGOOCOhhSp5SqIYoNrERM/rs:fit/g:sm/q:90/h:596/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTU0NTY4/NTctMTQ0ODQzNTQ4/My04ODEzLmpwZWc.jpeg', NOW()),
(4, 'Time Out', 'The Dave Brubeck Quartet', 1959, 'Jazz', 'One of the best-selling jazz albums of all time, featuring the famous track "Take Five".', 'https://i.discogs.com/tz4tsa5_pTztKx_mWvRvKp7jZ2YyztvF69PTEmVFlLg/rs:fit/g:sm/q:90/h:600/w:591/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEyMzg0/NTAyLTE1NjQ4NDQ1/MTMtMTEwNi5qcGVn.jpeg', NOW()),
(4, 'Chet Baker Sings', 'Chet Baker', 1956, 'Jazz', 'An album showcasing Baker''s smooth vocals alongside his trumpet playing.', 'https://i.discogs.com/kkB3vl0JPI3BsUswgOzz474KcgJk3ItfKFbS03FFiLE/rs:fit/g:sm/q:90/h:600/w:596/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTExMDg0/NjUyLTE1MDk1NjE3/NzgtMjQ3My5qcGVn.jpeg', NOW()),
(4, 'Blue Train', 'John Coltrane', 1957, 'Jazz', 'Although Coltrane is more associated with hard bop, this album has cool jazz influences.', 'https://i.discogs.com/ebbggnVeaR0P2u7UGljGIVnhx1LaxVNMMZiyLvH2VrM/rs:fit/g:sm/q:90/h:505/w:500/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTgwNjcw/MDMtMTQ1NDUyODYy/My0zNDkwLmpwZWc.jpeg', NOW()),
(4, 'Kind of Blue', 'Miles Davis', 1959, 'Jazz', 'Widely regarded as one of the greatest jazz albums of all time.', 'https://i.discogs.com/wjjMk1xCKdaPbsUbaXWzHBNi3K-fmt3CYkQGqt0c_Z8/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTYyNzYx/ODMtMTY3NzAwMzM5/Ni0yMDQ1LmpwZWc.jpeg', NOW()),
(4, 'Getz/Gilberto', 'Stan Getz and João Gilberto', 1964, 'Jazz', 'A collaboration between Stan Getz and Brazilian musician João Gilberto, featuring the hit "The Girl from Ipanema".', 'https://i.discogs.com/snOjVGbcA1MCeUThkeMWLjRyl8zjOqQ2BFWclMBcET8/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE3MDg4/NC0xMzI0MjQ4OTkw/LmpwZWc.jpeg', NOW()),
(4, 'Jazz Impressions of Black Orpheus', 'Vince Guaraldi Trio', 1962, 'Jazz', 'Known for its relaxed and melodic style, this album features the famous track "Cast Your Fate to the Wind".', 'https://i.discogs.com/zmUY39mwv3arExqMq5XV3RJ-gu2gs1pX5IV9PC2AcGc/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMzMTUw/MTUtMTY2NDg3MTA0/NS01NzE5LnBuZw.jpeg', NOW()),
(4, 'The Sidewinder', 'Lee Morgan', 1964, 'Jazz', 'A pivotal album in both the hard bop and cool jazz genres.', 'https://i.discogs.com/aJPE1UkOs5TR_jM3dy0S2o_1ww3kOgIH2gZ0lPbbUCE/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTU3OTg1/Mi0xMzUyMDUwMTQ0/LTgzMDAuanBlZw.jpeg', NOW()),
(4, 'Cool Struttin', 'Sonny Clark', 1958, 'Jazz', 'A quintessential cool jazz album featuring notable performances by Art Farmer and Jackie McLean.', 'https://i.discogs.com/SF9iv5qmCN5JEgsvAfdVyigc8zJQYbViZ3nNv4b0eEc/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE0NDUz/NjItMTQzNzUwNzMz/NC02Nzk0LmpwZWc.jpeg', NOW()),
(4, 'The Sermon!', 'Jimmy Smith', 1959, 'Jazz', 'An album that combines cool jazz with elements of soul jazz, featuring Lee Morgan and Lou Donaldson.', 'https://i.discogs.com/E2rWWkK5c4B85pHLUT-Oakqs0PWMGmLC2uJaA51IRrw/rs:fit/g:sm/q:90/h:595/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE1ODE1/OTAzLTE1OTgzMTI4/ODItNDQwMS5qcGVn.jpeg', NOW()),
(4, 'Legend', 'Bob Marley and the Wailers', 1984, 'Reggae', 'The best-selling reggae album of all time, featuring hits like "No Woman, No Cry" and "Redemption Song".', 'https://i.discogs.com/vLVptBfro38CQ49Ox99ADJWXAesfPj5FvXgOQNnne-M/rs:fit/g:sm/q:90/h:594/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTUwOTIz/NS0xMjE2MTY4MTgz/LmpwZWc.jpeg', NOW()),
(4, 'Catch a Fire', 'Bob Marley and the Wailers', 1973, 'Reggae', 'The album that introduced Bob Marley to an international audience, known for tracks like "Stir It Up".', 'https://i.discogs.com/eO1-I700dfw92SXk0_KaDeBYewo_ly5kpoPsgI5kGvk/rs:fit/g:sm/q:90/h:433/w:450/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTc1Mzkw/OTEtMTQ0MzYwNTQ2/OS05OTc5LmpwZWc.jpeg', NOW()),
(4, 'Two Sevens Clash', 'Culture', 1977, 'Reggae', 'A classic roots reggae album that predicted apocalypse in 1977.', 'https://i.discogs.com/_OC-IUEPqf4HQ47JoJnPislkdLNFAsYoa2_IysLCS0c/rs:fit/g:sm/q:90/h:600/w:599/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEzMjE5/ODUxLTE1NTAxODAy/OTItMzAyNS5qcGVn.jpeg', NOW()),
(4, 'Night Nurse', 'Gregory Isaacs', 1982, 'Reggae', 'A smooth reggae album featuring the popular title track "Night Nurse".', 'https://i.discogs.com/8azAbL0Uxj4CkUFCUhQEEB4NH-g3VxmItBzxYsbRLoU/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTQ1NTAz/MC0xNDE1NTgwNjc1/LTI4MzUuanBlZw.jpeg', NOW()),

(4, 'Symphony No. 5', 'Gustav Mahler', 1904, 'Classical', 'A major symphonic work known for its emotional range and the famous Adagietto movement.', 'https://i.discogs.com/tnnWY8R9cCeTo0_vayoZyQ7lkCwqKeWyjj0ICUVTY5M/rs:fit/g:sm/q:90/h:600/w:590/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE5MDIz/NjUtMTI1MTI1ODU2/NC5qcGVn.jpeg', NOW()),

(4, 'Red Headed Stranger', 'Willie Nelson', 1975, 'Country', 'A classic concept album that is considered one of Willie Nelson''s greatest works.', 'https://i.discogs.com/fhat5CADYWANhC1T0U-kY4l9dmgeU2VCB0HtMVVqWVQ/rs:fit/g:sm/q:90/h:598/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE1NjA0/NTAtMTUzOTgzNjE4/OC01OTMzLmpwZWc.jpeg', NOW()),

(4, 'The Gambler', 'Kenny Rogers', 1978, 'Country', 'Featuring the iconic title track "The Gambler", this album became one of Kenny Rogers'' most successful releases.', 'https://i.discogs.com/GOA9lxitECEoiTeJdT_7zKk5cAwpZzC9pZcZo0_kR1I/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTg5MDkx/Ni0xMzU2NTUxMzUx/LTc4MDIuanBlZw.jpeg', NOW()),
(4, 'Tangled Up in Blue', 'Bob Dylan', 1975, 'Country', 'Although primarily a rock album, it features country influences and is considered a classic in the genre.', 'https://i.discogs.com/wrItLkoa_RFoDIihIIGneRPIZxgnQvmhqYcfZJiIgOo/rs:fit/g:sm/q:90/h:593/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTIxMzM5/MjAtMTM0MTE5NTAz/Mi05MDY4LmpwZWc.jpeg', NOW()),
(4, 'Rihanna', 'Rated R', 2009, 'R&B', 'An album showcasing a darker and edgier side of Rihanna with tracks like "Russian Roulette".', 'https://i.discogs.com/cOz0vUhtp7l-OJZuzkuVcCBqjfyqh2j0jaDfNdOTQEU/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTcwOTUw/MzktMTQzMzYwNjE0/Mi05ODQwLmpwZWc.jpeg', NOW()),
(4, 'Led Zeppelin IV', 'Led Zeppelin', 1971, 'Rock', 'Featuring iconic tracks like "Stairway to Heaven" and "Black Dog".', 'https://i.discogs.com/yFq3X0xZMxIVHIFgmbrsPvJHXLJCfVLWs60AL4XS4bs/rs:fit/g:sm/q:90/h:598/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEwMTU0/NjUtMTM2NjMxMTg2/Ny0yNzg1LmpwZWc.jpeg', NOW()),
(4, 'A Night at the Opera', 'Queen', 1975, 'Rock', 'Known for the operatic epic "Bohemian Rhapsody".', 'https://i.discogs.com/2GXnNYolz0ciUnj8-ycSwQ8Uuy0Qu7LCfiZivZ0p_bo/rs:fit/g:sm/q:90/h:594/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTYxMjc4/MC0xNTQxMzY3MTQ1/LTIxMjcuanBlZw.jpeg', NOW()),

(4, 'Appetite for Destruction', 'Guns N'' Roses', 1987, 'Rock', 'A groundbreaking debut album with hits like "Sweet Child O'' Mine" and "Welcome to the Jungle".', 'https://i.discogs.com/VQy0HOhX4RiGLIg0LXi-RiZMJG8wtJDvFaBbarerjyA/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM4Mzc3/Ny0xMTczNTQzMzU5/LmpwZWc.jpeg', NOW()),

(4, 'Who''s Next', 'The Who', 1971, 'Rock', 'An influential album featuring classic rock anthems like "Baba O''Riley" and "Behind Blue Eyes".', 'https://i.discogs.com/g97FVTu96ctj-AOw2zjmJrz3I2ZPyipQuWwUgFQ_YlI/rs:fit/g:sm/q:90/h:600/w:596/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTQ4NzQ2/NC0xNTg3Mzc2MjQw/LTQ5NDEuanBlZw.jpeg', NOW()),
(4, 'Californication', 'Red Hot Chili Peppers', 1999, 'Rock', 'Marked the return of guitarist John Frusciante and includes hits like "Scar Tissue" and "Otherside".', 'https://i.discogs.com/CyHLgusU6vKUZ6AZbiWlLpgtKm2mT05k0NdV5LQvMjM/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEyNjY4/MDQtMTQ2MTI5MDIx/Ni03MDEwLmpwZWc.jpeg', NOW()),

(4, 'Like a Virgin', 'Madonna', 1984, 'Pop', 'An album that solidified Madonna''s status as a pop icon with hits like "Material Girl".', 'https://i.discogs.com/GK85qS-oBUfj_8rjFHQaO73HW16U51qRS5EEV5ZDuGg/rs:fit/g:sm/q:90/h:595/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTQyODk0/MDgtMTQxODg4NjE4/NC0xMjc2LmpwZWc.jpeg', NOW()),

(4, 'Christmas', 'Michael Bublé', 2011, 'Holiday', 'A popular modern holiday album featuring classics like "All I Want for Christmas Is You".', 'https://i.discogs.com/G6TvFR3BZ2YUT0puLXveM2xgxjfT-s62VzDPFtcL2rE/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMxOTU1/MTItMTMyNDc5NDgz/Ny5qcGVn.jpeg', NOW()),
(4, 'Let It Snow', 'Frank Sinatra', 1957, 'Holiday', 'A classic holiday album with Sinatra''s smooth vocals on traditional Christmas songs.', 'https://i.discogs.com/4eU3Qp6vFc5t9bSvFUbLnzSN80C6ReUYjlt8Ppoqxew/rs:fit/g:sm/q:90/h:600/w:591/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI0Nzcx/NzQ5LTE2NjUzNDUz/NjQtMjI3Ny5qcGVn.jpeg', NOW()),
(4, 'A Charlie Brown Christmas', 'Vince Guaraldi Trio', 1965, 'Holiday', 'Iconic jazz album from the beloved Peanuts special, featuring "Linus and Lucy".', 'https://i.discogs.com/fX8wAS69mRFpoLgU4Gy_sNjQ7BzSOHs1z8EzPbutnr4/rs:fit/g:sm/q:90/h:570/w:568/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE2Mjc3/MzEtMTMzNjYzMTg4/MC01MDQ5LmpwZWc.jpeg', NOW()),
(4, 'Merry Christmas', 'Mariah Carey', 1994, 'Holiday', 'One of the best-selling holiday albums of all time, including the hit "All I Want for Christmas Is You".', 'https://i.discogs.com/08wNoRk1F5qZRH-lqZNqPs-svvjW23bFN8U04MAJ89s/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEyNDcx/OTYtMTQyMjU0MTgw/MC00ODgwLmpwZWc.jpeg', NOW()),
(4, 'The Christmas Song', 'Nat King Cole', 1960, 'Holiday', 'Includes the timeless classic "The Christmas Song (Chestnuts Roasting on an Open Fire)".', 'https://i.discogs.com/tizWkEL_MIn6Wqg1rvYnUq_DJDlQ4HNfIG1SdS3JcuM/rs:fit/g:sm/q:90/h:597/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTcyMjM1/OC0xMjcwODQzODU3/LmpwZWc.jpeg', NOW()),
(4, 'Christmas with the Rat Pack', 'Frank Sinatra, Dean Martin, Sammy Davis Jr.', 1960, 'Holiday', 'A collection of holiday tunes from the legendary Rat Pack.', 'https://i.discogs.com/t1Bb4N2EZGtMKEy5WixKlzxRTvh_79sjvRUL-mDui_A/rs:fit/g:sm/q:90/h:600/w:591/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTQxNzAw/ODEtMTQyNjk5MTE4/MC04MjExLmpwZWc.jpeg', NOW()),
(4, 'White Christmas', 'Bing Crosby', 1942, 'Holiday', 'Featuring the classic title track "White Christmas", a staple of holiday music.', 'https://i.discogs.com/tiDi3f24k8IE0qrJ91dBPBFco_jISWgSvSytoxmly-0/rs:fit/g:sm/q:90/h:600/w:598/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM5NDU3/NjYtMTQ3NTI2Mzkx/NC03MDM1LmpwZWc.jpeg', NOW()),
(4, 'Christmas Kisses', 'Ariana Grande', 2013, 'Holiday', 'An EP featuring Ariana Grande''s take on classic holiday songs.', 'https://i.discogs.com/p4P_-_rnGCjrSpaxXKM6J32O_i2POIFy03MXsvhAHPM/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTUyMjM2/MjMtMTM4Nzk5ODYw/Ni00MzYzLmpwZWc.jpeg', NOW()),
(4, 'Elf: Original Motion Picture Soundtrack', 'Various Artists', 2003, 'Holiday', 'Soundtrack from the popular holiday film "Elf", including festive songs from various artists.', 'https://i.discogs.com/Fca73iLIngXUxeu1FZ_pO9b74KwrbQy6Pr9MLxSg5R8/rs:fit/g:sm/q:90/h:595/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTIyNDg0/MTU5LTE2OTY3NjU4/MjEtMjc2NS5qcGVn.jpeg', NOW()),
(4, 'Animals', 'Pink Floyd', 1977, 'Rock', 'A concept album with themes of societal criticism and animal imagery.', 'https://i.discogs.com/_hYJ-UiHBq0KtuIlz26o-4Ar82o9589HIFIE5XOXuVU/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM5MTMy/Mi0xNjkxNTYzMjc4/LTYwODAuanBlZw.jpeg', NOW()),
(4, 'Wish You Were Here', 'Pink Floyd', 1975, 'Rock', 'Famous for its title track and "Shine On You Crazy Diamond", a tribute to Syd Barrett.', 'https://i.discogs.com/pZnTKUeiKsxSyvX_87YMgccx0bq5sjqThFH9iSNAtAY/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE2MjEx/ODEyLTE2MzczMzYw/OTctOTI4MC5qcGVn.jpeg', NOW()),
(4, 'Meddle', 'Pink Floyd', 1971, 'Rock', 'Known for the epic track "Echoes", which dominates the second half of the album.', 'https://i.discogs.com/nlcHURJ-xZgDIezGAne4lRoiOZJYbb-qHxf7NMfwTQw/rs:fit/g:sm/q:90/h:592/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTQxMzc0/OTMtMTUzNzIxNjkz/NS05NzUzLmpwZWc.jpeg', NOW()),
(4, 'The Piper at the Gates of Dawn', 'Pink Floyd', 1967, 'Rock', 'The debut album, characterized by its psychedelic sound and Syd Barrett''s influence.', 'https://i.discogs.com/hb2vfQoi-csFMlMpGEHrDNUFVlOnLUVQgWYyFyXOQNs/rs:fit/g:sm/q:90/h:596/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI5MDEy/MDMtMTYwNzE4NTk0/OS0xNDMxLmpwZWc.jpeg', NOW()),
(4, 'A Saucerful of Secrets', 'Pink Floyd', 1968, 'Rock', 'The second album, which marks the beginning of the transition from Syd Barrett to David Gilmour.', 'https://i.discogs.com/Jcs2saffPTQvg8a4HmnhdagkrChDcewBA5Xj0tum9Sk/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEzODIz/ODctMTU1NTU0MzU4/Ny00NzAzLmpwZWc.jpeg', NOW()),
(4, 'Obscured by Clouds', 'Pink Floyd', 1972, 'Rock', 'A soundtrack album for the film "La Vallée", featuring a mix of rock and instrumental tracks.', 'https://i.discogs.com/c1B9Jw9ruSJqyp42-VkC2cxSyzq7LMQI7GztAeIkmrA/rs:fit/g:sm/q:90/h:600/w:597/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMwOTI0/MTItMTMxNTM1MTI4/OS5qcGVn.jpeg', NOW()),
(4, 'The Final Cut', 'Pink Floyd', 1983, 'Rock', 'A concept album and the last album with Roger Waters, focusing on themes of war and politics.', 'https://i.discogs.com/nQ9TyddcSe2CL0rjRlvQIW8ShAeO7eBAEjE6BRpH5Hg/rs:fit/g:sm/q:90/h:600/w:566/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEyMDYx/MzQtMTMxODA5MDc3/Ni5qcGVn.jpeg', NOW()),
(4, 'Momentary Lapse of Reason', 'Pink Floyd', 1987, 'Rock', 'The first album after Roger Waters left the band, featuring a more polished and electronic sound.', 'https://i.discogs.com/9cWYbmG22n9I5X2Pfz4_U3pscmLpy1gffxZQwswIG4Q/rs:fit/g:sm/q:90/h:595/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEyMDE3/NzItMTQ0NTIyNTY5/Ni0yNjg1LmpwZWc.jpeg', NOW()),
(4, 'Paranoid', 'Black Sabbath', 1970, 'Rock', 'One of the pioneering albums of heavy metal.', 'https://i.discogs.com/IktWj7o-ctHsGt3t-9cvGWCqUhh33G-tVgixfHKA6dA/rs:fit/g:sm/q:90/h:564/w:575/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTY5Njc3/Mi0xMzg5NjIyMTk4/LTU3MzUuanBlZw.jpeg', NOW()),
(4, 'Master of Puppets', 'Metallica', 1986, 'Rock', 'Highly influential metal album featuring complex compositions.', 'https://i.discogs.com/WIcmVaAsfOwxgaKApPMciVitogXJEkSAl1TyIhxTNRw/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE1NDk2/MzYtMTI2NTk0ODA5/NC5qcGVn.jpeg', NOW()),
(4, 'The Number of the Beast', 'Iron Maiden', 1982, 'Rock', 'Iconic album featuring classic heavy metal themes.', 'https://i.discogs.com/-wHpEmzsOPDHv755TdLKf4a4rS0i-zCmrdu8492KxOk/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE0NjYy/OTktMTY0NTU0MTQx/NC0yNDk0LmpwZWc.jpeg', NOW()),
(4, 'Painkiller', 'Judas Priest', 1990, 'Rock', 'Known for its speed metal influences and powerful vocals.', 'https://i.discogs.com/-OfsxmQv-4D21nNeludWOwFvtMTQYVJIhc8_cT8PKbE/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE2MTIy/OTItMTU5NTg5NDkx/My0zOTQ1LmpwZWc.jpeg', NOW()),
(4, 'British Steel', 'Judas Priest', 1980, 'Rock', 'A landmark album in the heavy metal genre with a more accessible sound.', 'https://i.discogs.com/-Ms8k-yQdyAuHuXgAN0b6nlJYLtZF8a0kP4DnSEGVBA/rs:fit/g:sm/q:90/h:597/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE1Njgw/ODEtMTY5MzQxODAw/My05NDMwLmpwZWc.jpeg', NOW()),
(4, 'Reign in Blood', 'Slayer', 1986, 'Rock', 'A seminal album in thrash metal with intense speed and aggression.', 'https://i.discogs.com/ssK5RzyVR9-gBLkS40Fybz5QTvvVsaHiXj9lGfvf0Ew/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM3NzUy/MS0xNjM5MjM4OTg2/LTU1MDMuanBlZw.jpeg', NOW()),
(4, 'Hell Awaits', 'Slayer', 1985, 'Rock', 'Famous for its dark themes and complex arrangements.', 'https://i.discogs.com/S2vkQq_tAqfEulYGJF0KtZ4Q6VNSjqXFCVk_s9MONf0/rs:fit/g:sm/q:90/h:596/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEwMjY3/MTMtMTYzNDY0OTE4/MS0zMjg1LmpwZWc.jpeg', NOW()),
(4, 'Holy Diver', 'Dio', 1983, 'Rock', 'Featuring classic heavy metal sound with powerful vocals and fantasy themes.', 'https://i.discogs.com/Tebkvc5nA9AyMVaxBHgLRnVQFEjP6HZEe81vCrjZGdA/rs:fit/g:sm/q:90/h:598/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEzMzE2/Mzg1LTE2NDg1Mzg3/MTctNTcyMC5qcGVn.jpeg', NOW());

INSERT INTO collections (user_id, title, description) VALUES
(4, 'Summer Jams', 'Songs I like listening to on hot days while taking a drive.'),
(4, 'The Heaviest Metal', 'So heavy I cant even lift the albums.'),
(4, 'Rare Release', 'Here are some of my favorite rare releases.'),
(4, 'Tis The Season', 'I like collecting Christmas albums , here are some of my favorites.'),
(4, 'Mr Pink', 'This is my Pink Floyd collection.'),
(4, 'Signed Records', 'This is a collection of all my records that have signatures on them.'),
(4, 'Vintage Vinyls', 'My vintage collection'),
(4, 'Smooth Jazz Times', 'So smooth the stylus wont work.');

 INSERT INTO album_collections (album_id, collection_id) VALUES
(1, 1),
(8, 1),
(9, 1),
(10, 1),
(12, 1),
(27, 1),
(28, 1),
(112, 1),
(2, 2),
(3, 2),
(119, 2),
(120, 2),
(121, 2),
(122, 2),
(123, 2),
(124, 2),
(125, 2),
(126, 2),
(11, 8),
(13, 8),
(15, 8),
(17, 8),
(19, 8),
(11, 7),
(12, 8),
(13, 7),
(22, 7),
(61, 7),
(67, 7),
(81, 7),
(82, 7),
(112, 7),
(116, 7),
(2, 6),
(117, 6),
(21, 6),
(95, 6),
(118, 6),
(84, 6),
(90, 6),
(88, 6),
(3, 5),
(7, 5),
(111, 5),
(112, 5),
(113, 5),
(114, 5),
(115, 5),
(116, 5),
(117, 5),
(118, 5),
(101, 4),
(102, 4),
(104, 4),
(105, 4),
(106, 4),
(107, 4),
(108, 4),
(109, 4),
(110, 4),
(2, 3),
(112, 3),
(11, 3),
(19, 3),
(22, 3),
(58, 3),
(66, 3),
(81, 3);

COMMIT TRANSACTION;

